name: Build SU
on:
  push:
    branches: [ "main", "ci" ]
    paths:
      - '.github/workflows/build-su.yml'
      - 'userspace/su/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'userspace/su/**'
jobs:
  build-su:
    name: Build userspace su
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Build su
      working-directory: ./userspace/su
      run: $ANDROID_NDK/ndk-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: su
        path: ./userspace/su/libs
